version: '3'
services:
    nginx:
      image: nginx:latest
      ports:
          - "80:80"
      volumes:
          - ./src:/home/user/www
          - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      links:
        - php
    php:
      image: php:7.3-fpm
      volumes:
        - ./src:/home/user/www
